import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateNotificationTypes1782361622048 implements MigrationInterface {
    name = 'UpdateNotificationTypes1782361622048'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "recurring_availability" DROP CONSTRAINT "recurring_availability_doctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "custom_availability" DROP CONSTRAINT "custom_availability_doctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "fk_appointments_doctor"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "fk_appointments_patient"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "fk_appointments_stream_slot"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "fk_appointments_wave_schedule"`);
        await queryRunner.query(`ALTER TABLE "stream_slots" DROP CONSTRAINT "fk_stream_slots_doctor"`);
        await queryRunner.query(`ALTER TABLE "wave_schedules" DROP CONSTRAINT "fk_wave_schedules_doctor"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_patientId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_patient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_doctor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stream_slots_doctor_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wave_schedules_doctor_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_patientId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_patientId_isRead"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_patientId_createdAt"`);
        await queryRunner.query(`ALTER TABLE "custom_availability" RENAME COLUMN "doctorId" TO "doctorProfileId"`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" DROP COLUMN "doctorId"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "schedulingType"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_schedulingtype_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "streamSlotId"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "waveScheduleId"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "waveToken"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" ADD "doctorProfileId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" DROP COLUMN "dayOfWeek"`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" ADD "dayOfWeek" "public"."recurring_availability_dayofweek_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "appointmentDate"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "appointmentDate" character varying NOT NULL DEFAULT '2026-06-26'`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "appointmentDate" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "startTime" character varying NOT NULL DEFAULT '10:00'`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "startTime" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "endTime" character varying NOT NULL DEFAULT '10:30'`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "endTime" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."appointments_status_enum" RENAME TO "appointments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('CONFIRMED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" TYPE "public"."appointments_status_enum" USING "status"::"text"::"public"."appointments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'CONFIRMED'`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_enum" RENAME TO "notification_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('APPOINTMENT_BOOKED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESCHEDULED', 'APPOINTMENT_REMINDER', 'FOLLOW_UP_REMINDER')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum" USING "type"::"text"::"public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying NOT NULL DEFAULT 'Notification'`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" ADD CONSTRAINT "FK_988d39de6521504d5dc9ac0b9f5" FOREIGN KEY ("doctorProfileId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_availability" ADD CONSTRAINT "FK_4b01248ade4901e776f8ed260f8" FOREIGN KEY ("doctorProfileId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_0c1af27b469cb8dca420c160d65" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "patient_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stream_slots" ADD CONSTRAINT "FK_fd41dffa22b3935f03ede45aa07" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wave_schedules" ADD CONSTRAINT "FK_e14577b3def0eea7b977cd31f17" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wave_schedules" DROP CONSTRAINT "FK_e14577b3def0eea7b977cd31f17"`);
        await queryRunner.query(`ALTER TABLE "stream_slots" DROP CONSTRAINT "FK_fd41dffa22b3935f03ede45aa07"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_0c1af27b469cb8dca420c160d65"`);
        await queryRunner.query(`ALTER TABLE "custom_availability" DROP CONSTRAINT "FK_4b01248ade4901e776f8ed260f8"`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" DROP CONSTRAINT "FK_988d39de6521504d5dc9ac0b9f5"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum_old" AS ENUM('APPOINTMENT_BOOKED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESCHEDULED', 'APPOINTMENT_REMINDER', 'FOLLOW_UP_REMINDER')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notification_type_enum_old" USING "type"::"text"::"public"."notification_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_enum_old" RENAME TO "notification_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum_old" AS ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED')`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" TYPE "public"."appointments_status_enum_old" USING "status"::"text"::"public"."appointments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'CONFIRMED'`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."appointments_status_enum_old" RENAME TO "appointments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "endTime" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "startTime" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "appointmentDate"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "appointmentDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" DROP COLUMN "dayOfWeek"`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" ADD "dayOfWeek" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" DROP COLUMN "doctorProfileId"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "waveToken" integer`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "waveScheduleId" integer`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "streamSlotId" integer`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_schedulingtype_enum" AS ENUM('STREAM', 'WAVE')`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "schedulingType" "public"."appointments_schedulingtype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" ADD "doctorId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "custom_availability" RENAME COLUMN "doctorProfileId" TO "doctorId"`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_patientId_createdAt" ON "notifications" ("createdAt", "patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_patientId_isRead" ON "notifications" ("isRead", "patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_patientId" ON "notifications" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "idx_wave_schedules_doctor_date" ON "wave_schedules" ("date", "doctorId") `);
        await queryRunner.query(`CREATE INDEX "idx_stream_slots_doctor_date" ON "stream_slots" ("date", "doctorId") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_date" ON "appointments" ("appointmentDate") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_doctor" ON "appointments" ("doctorId") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_patient" ON "appointments" ("patientId") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patient_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wave_schedules" ADD CONSTRAINT "fk_wave_schedules_doctor" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stream_slots" ADD CONSTRAINT "fk_stream_slots_doctor" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "fk_appointments_wave_schedule" FOREIGN KEY ("waveScheduleId") REFERENCES "wave_schedules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "fk_appointments_stream_slot" FOREIGN KEY ("streamSlotId") REFERENCES "stream_slots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "fk_appointments_patient" FOREIGN KEY ("patientId") REFERENCES "patient_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "fk_appointments_doctor" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_availability" ADD CONSTRAINT "custom_availability_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_availability" ADD CONSTRAINT "recurring_availability_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctor_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
